import { seoHead, generateDiscovery } from './seo.mjs';
import { writeFile, readdir, readFile } from 'node:fs/promises';
import { projects } from '../src/projects.mjs';
const linkedin = 'https://www.linkedin.com/in/lucas-aveline/';
const ext = ' target="_blank" rel="noopener noreferrer"';
const routes = [['Accueil','index.html'],['Réalisations','pages/realisations.html'],['Jeux & autres','pages/jeux.html'],['Expériences','pages/experiences.html'],['Formations','pages/formations.html'],['Veille','pages/veille.html']];
const escape = value => value.replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;');
const tags = values => `<div class="tags">${values.map(value=>`<span>${value}</span>`).join('')}</div>`;
function card(project, prefix) {
 const link = project.url ? `<a href="${project.url.startsWith('http')?project.url:prefix+project.url}"${project.url.startsWith('http')?ext:''} class="card-action">${project.action}<span>↗</span></a>` : `<button class="card-action" data-project="${project.id}">${project.action}<span>↗</span></button>`;
 return `<article class="project-card" data-category="${project.category}" data-search="${escape([project.title,...project.tags,project.description].join(' '))}"><div class="card-media ${project.id}" aria-hidden="true">${project.image?`<img src="${prefix}src/img/${project.image}" alt="" loading="lazy" width="720" height="450">`:'<div class="carbon-graphic"><span class="ring"></span><span class="ring"></span><span class="ring"></span><strong>CO₂<sup>↘</sup></strong></div>'}<span class="media-label">${project.label}</span></div><div class="card-body"><h3>${project.title}</h3><p>${project.description}</p>${tags(project.tags)}${link}</div></article>`;
}
const head = (eyebrow,title,description) => `<div class="page-heading"><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p>${description}</p></div>`;
const sectionHead = (number,title,link='') => `<div class="section-heading"><div><p class="eyebrow">${number}</p><h2>${title}</h2></div>${link}</div>`;
function filters(game=false) { return `<div class="gallery-tools"><div class="filters" role="group" aria-label="Filtrer les réalisations">${(game?[['all','Tout tester'],['jeu','Jeux'],['outil','Outils interactifs'],['interface','Interfaces']]:[['all','Tout voir'],['web','Applications'],['collectif','Collectif']]).map(([id,label],i)=>`<button data-filter="${id}" aria-pressed="${i===0}">${label}</button>`).join('')}</div><label class="search"><span class="sr-only">Rechercher un projet</span><span aria-hidden="true">⌕</span><input type="search" id="project-search" placeholder="Rechercher un projet…"></label></div>`; }
const gallery = (list,prefix,game=false) => `${filters(game)}<p class="results" role="status" id="filter-status">${list.length} réalisations</p><div class="project-grid">${list.map(project=>card(project,prefix)).join('')}</div><div class="empty-state" hidden><h3>Aucun projet trouvé.</h3><p>Essayez un autre mot-clé ou réinitialisez les filtres.</p><button class="button secondary" id="reset-filters">Tout afficher</button></div>`;
async function page(path,title,body) {
 const prefix=path==='index.html'?'':'../';
 const html=`<!doctype html>
<html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} — Lucas Aveline</title>${seoHead(path,title)}<meta name="theme-color" content="#f7f8fc"><link rel="icon" href="${prefix}src/img/favicon.ico"><script src="${prefix}src/theme.js"></script><link rel="stylesheet" href="${prefix}src/portfolio.css"><link rel="stylesheet" href="${prefix}src/theme.css"><script type="module" src="${prefix}src/portfolio.js"></script></head>
<body data-root="${prefix}"><a class="skip" href="#main">Aller au contenu</a><header class="site-header"><div class="header-inner"><a class="brand" href="${prefix}index.html" aria-label="Lucas Aveline, accueil"><span class="monogram">la<span>.</span></span><span>Lucas Aveline<small>COORDINATION IT & SOLUTIONS DIGITALES</small></span></a><button class="theme-toggle" type="button" aria-label="Changer le thème" title="Changer le thème"><span aria-hidden="true" class="theme-icon">◐</span><span class="theme-label">Thème</span></button><button class="menu-toggle" aria-expanded="false" aria-controls="navigation"><span class="menu-label">Menu</span><span class="menu-symbol" aria-hidden="true">☰</span></button><nav id="navigation" aria-label="Navigation principale"><span class="mobile-nav-label">EXPLORER LE PORTFOLIO</span>${routes.map(([label,url])=>`<a href="${prefix}${url}"${url===path?' aria-current="page"':''}>${label}</a>`).join('')}<a class="nav-contact" href="${prefix}pages/contact.html"${path==='pages/contact.html'?' aria-current="page"':''}>Contact ↗</a><a class="nav-cv" href="${prefix}src/files/CV-Lucas-Aveline-IT-Project-Manager-2026.pdf" download aria-label="Télécharger mon CV 2026">CV <span aria-hidden="true">↓</span></a></nav></div></header>
<main id="main">${body}</main><footer class="footer wrap"><div><a class="brand" href="${prefix}index.html"><span class="monogram">la<span>.</span></span><span>Lucas Aveline<small>PORTFOLIO 2026</small></span></a><p>Coordinateur IT & fondateur de <a class="inline-company" href="https://nexsecure.fr/"${ext}>NexSecure ↗</a>.</p></div><div class="footer-links"><a href="${prefix}pages/realisations.html">Toutes les réalisations</a><a href="${prefix}pages/formations.html">Diplômes & formations</a><a href="${prefix}src/files/CV-Lucas-Aveline-IT-Project-Manager-2026.pdf" download>Télécharger mon CV 2026 ↓</a></div><div class="footer-links"><a href="${linkedin}"${ext}>LinkedIn ↗</a><a href="https://github.com/Sunlama0"${ext}>GitHub ↗</a><a href="#main">Retour en haut ↑</a></div><div class="footer-bottom"><span>© 2026 Lucas Aveline</span><span>Conçu pour explorer. Et pour jouer.</span></div></footer>
<dialog id="project-dialog" aria-labelledby="dialog-title"><button class="dialog-close" aria-label="Fermer le détail du projet">✕</button><p class="eyebrow" id="dialog-category"></p><h2 id="dialog-title"></h2><img id="dialog-image" alt=""><p id="dialog-description"></p><div class="tags" id="dialog-tags"></div><a href="${linkedin}"${ext} class="button">Échanger sur ce projet ↗</a></dialog></body></html>`;
 await writeFile(path,html);
}
const files = await readdir('src/files');
const synthesis=files.find(file=>file.startsWith('Tableau'));
const docs=(prefix)=>`<div class="document-grid"><a class="document" href="${prefix}src/files/CV-Lucas-Aveline-IT-Project-Manager-2026.pdf" download><span class="file-icon">PDF</span><div><h3>CV · IT Project Manager 2026</h3><p>Télécharger mon CV actualisé · PDF</p></div><span>↗</span></a><a class="document" href="${prefix}src/files/${synthesis}"${ext}><span class="file-icon">PDF</span><div><h3>Tableau de synthèse E4</h3><p>Compétences et réalisations de formation</p></div><span>↗</span></a><a class="document" href="${prefix}src/files/attestation-pix.pdf"${ext}><span class="file-icon">PIX</span><div><h3>Certification Pix</h3><p>Mars 2023 · Compétences numériques</p></div><span>↗</span></a>${[1,2,3,4,5].map(n=>`<a class="document" href="${prefix}src/files/Certificat_CNIL_${n}.pdf"${ext}><span class="file-icon">CNIL</span><div><h3>RGPD · Module ${n}</h3><p>Septembre 2024 · Attestation CNIL</p></div><span>↗</span></a>`).join('')}</div>`;
const contact=(prefix)=>`<section class="contact-banner wrap" id="contact"><div><p class="eyebrow">ET SI ON EN PARLAIT ?</p><h2>Une idée. Un projet.<br><span>Un premier échange.</span></h2></div><a href="${prefix}pages/contact.html" class="button">Me contacter <span>↗</span></a></section>`;
await page('index.html','Portfolio 2026',`<section class="hero wrap"><div class="hero-copy"><p class="eyebrow"><span class="status-dot"></span> COORDINATEUR DE PROJETS IT · FONDATEUR DE NEXSECURE</p><h1>Lucas Aveline<span>Développer.<br>Connecter.<br><em>Faire avancer.</em></span></h1><p class="hero-description">Coordinateur de projets IT et fondateur de <a class="inline-company" href="https://nexsecure.fr/"${ext}>NexSecure ↗</a>, je relie les besoins métiers à la technique : cybersécurité, automatisation, développement et data.</p><div class="actions"><a class="button" href="pages/realisations.html">Explorer mes réalisations <span>↗</span></a><a class="button secondary" href="pages/experiences.html">Découvrir mon parcours <span>↗</span></a></div><div class="hero-social"><span>Paris & Île-de-France</span><span>/</span><a href="${linkedin}"${ext}>LinkedIn ↗</a><a href="https://github.com/Sunlama0"${ext}>GitHub ↗</a></div></div><div class="hero-visual"><a class="portrait-frame" href="https://www.linkedin.com/feed/update/urn:li:activity:7506621354692083712"${ext} aria-label="Voir la publication de Lucas Aveline sur LinkedIn (nouvel onglet)"><img src="src/img/lucas-2026.jpg" alt="Portrait de Lucas Aveline" width="1200" height="1600" fetchpriority="high"><div class="portrait-caption"><span>LUCAS AVELINE</span><span>2026 ↗</span></div></a><div class="floating-tag code-tag"><span>&lt;/&gt;</span> Piloter. Automatiser.<br>Sécuriser.</div><a class="floating-tag play-tag" href="pages/jeux.html"><span class="play-icon" aria-hidden="true"><svg viewBox="0 0 24 24" width="22" height="22" focusable="false"><path d="M9 5.5 19 12 9 18.5Z" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linejoin="round"/></svg></span><div>Une pause entre deux projets.<strong>10 expériences à tester ↗</strong></div></a></div></section><div class="stats-strip wrap"><div><strong>07</strong><span>réalisations à explorer</span></div><div><strong>10</strong><span>jeux, outils & interfaces</span></div><div><strong>08</strong><span>documents & certifications</span></div><a href="pages/formations.html#documents">Mon parcours, en détail <span>↗</span></a></div>
<section class="section wrap">${sectionHead('01 / EN LUMIÈRE','Du besoin à l’application.','<a class="text-link" href="pages/realisations.html">Toutes les réalisations <span>↗</span></a>')}<div class="project-grid featured-grid">${projects.slice(0,3).map(project=>card(project,'')).join('')}</div></section>
<section class="company-section wrap"><div class="company-heading"><p class="eyebrow">MON ENTREPRISE</p><h2>NexSecure<span>↗</span></h2><p>Des solutions numériques<br>pour les besoins du terrain.</p></div><div class="company-content"><p>Avec NexSecure, j’accompagne les entreprises dans la création de sites web et d’applications métier, l’automatisation de leurs processus et la sécurisation de leur informatique.</p><div class="company-services"><span>Sites & applications</span><span>Automatisation</span><span>Cybersécurité</span><span>Gestion IT</span></div><a class="button" href="https://nexsecure.fr/"${ext}>Découvrir NexSecure <span>↗</span></a></div></section><section class="wrap editorial-band"><div><p class="eyebrow">DE LA CURIOSITÉ À LA PRATIQUE</p><h2>La tech évolue.<br>Moi aussi.</h2></div><p>Des projets concrets, une veille régulière et le goût de l’expérimentation. J’apprends en construisant, en échangeant et en testant.</p><a class="text-link" href="pages/veille.html">Ouvrir mon journal de veille ↗</a></section>
<section class="section wrap skills-section"><div>${sectionHead('03 / COMPÉTENCES','Une boîte à outils.<br>Plusieurs façons de créer.')}<p class="section-intro">Cadrer un projet, automatiser un processus, sécuriser les accès ou exploiter les données : une approche technique au service des usages.</p><a class="text-link" href="pages/experiences.html">Découvrir mon parcours ↗</a></div><div class="skill-grid"><article><span class="skill-symbol">&lt;/&gt;</span><h3>Développement</h3><p>Laravel · Node.js · TypeScript · APIs</p></article><article><span class="skill-symbol">{ }</span><h3>Automatisation</h3><p>Power Apps · Power Automate · Python · PowerShell</p></article><article><span class="skill-symbol">⌘</span><h3>Data & BI</h3><p>SQL · Snowflake · Power BI</p></article><article><span class="skill-symbol">↗</span><h3>Cybersécurité & IT</h3><p>Entra ID · MFA/SSO · Microsoft 365 · Cloudflare</p></article></div></section>
<section class="wrap explore-section"><a href="pages/experiences.html"><span>04 / EXPÉRIENCES</span><h3>Le terrain professionnel ↗</h3><p>Mes expériences en entreprise et les projets auxquels j’ai contribué.</p></a><a href="pages/formations.html"><span>05 / FORMATIONS</span><h3>Apprendre & se spécialiser ↗</h3><p>Mon parcours de formation, mes diplômes et mes certifications.</p></a><a href="pages/veille.html"><span>06 / CURIOSITÉ</span><h3>Le journal de veille ↗</h3><p>Développement web, outils, IA et cloud : une veille actualisée automatiquement.</p></a></section>${contact('')}`);
await page('pages/realisations.html','Réalisations',`<section class="wrap section page-section">${head('APPLICATIONS MÉTIER · PROJETS COLLECTIFS','Concevoir. Développer. Livrer.<span class="heading-count">4</span>','Mes projets web, applications métier et expérimentations techniques. Chaque réalisation raconte une mise en pratique.')} ${gallery(projects.filter(project=>['web','collectif'].includes(project.category)),'../')}</section>${contact('../')}`);
await page('pages/jeux.html','Jeux interactifs & autres',`<section class="wrap section page-section">${head('LE PLAYGROUND · 10 EXPÉRIENCES','Jouer. Tester. Explorer.','Jeux interactifs, petits outils et interfaces : tout ce que vous pouvez essayer directement sur le site est réuni ici.')} ${gallery(projects.filter(project=>['jeu','outil','interface'].includes(project.category)),'../',true)}</section>`);
const profile = JSON.parse(await readFile('src/data/profile.json','utf8'));
const entry = item => `<article><p class="eyebrow">${escape(item.period)}</p><h2>${escape(item.title)}</h2><h3 class="entry-organization">${escape(item.organization)}</h3><p>${escape(item.description)}</p>${item.missions?`<ul>${item.missions.map(mission=>`<li>${escape(mission)}</li>`).join('')}</ul>`:''}${tags(item.tags || [])}${item.organization.startsWith('NexSecure')?`<a class="text-link company-entry-link" href="https://nexsecure.fr/"${ext}>Découvrir mon entreprise · nexsecure.fr ↗</a>`:''}</article>`;
await page('pages/experiences.html','Expériences professionnelles',`<section class="wrap section page-section">${head('LE PARCOURS PROFESSIONNEL','L’expérience du concret.','Des environnements, des équipes et des besoins réels. Mes expériences professionnelles et ce qu’elles m’ont appris.')}<div class="journey-layout"><aside class="profile-card"><img src="../src/img/lucas-2026.jpg" alt="Lucas Aveline" width="1200" height="1600"><h2>Lucas Aveline</h2><p>Coordination IT · Cybersécurité · Automatisation</p><a class="button" href="${linkedin}"${ext}>Mon profil LinkedIn ↗</a></aside><div><div class="timeline">${profile.experiences.map(entry).join('')}</div><section class="engagement-section"><p class="eyebrow">ENGAGEMENT & VIE ASSOCIATIVE</p><div class="timeline">${profile.engagements.map(entry).join('')}</div></section></div></div></section>${contact('../')}`);
await page('pages/formations.html','Formations & diplômes',`<section class="wrap section page-section">${head('LE PARCOURS ACADÉMIQUE','Apprendre. Puis aller plus loin.','Mes formations et certifications, du socle informatique aux projets collectifs.')}<div class="education-layout"><div class="timeline">${profile.education.map(entry).join('')}</div><aside class="education-note"><span class="note-symbol">↗</span><h2>Apprendre en faisant.</h2><p>Le hackathon 2026 de Sup de Vinci a été l’occasion de développer en équipe un prototype web et mobile autour de l’empreinte carbone.</p><a class="text-link" href="${projects[0].url}"${ext}>Découvrir cette expérience ↗</a></aside></div><section id="documents" class="documents-section">${sectionHead('DOCUMENTS & CERTIFICATIONS','Les pièces du parcours.')}<p class="section-intro">Mon CV 2026, mes attestations Pix et CNIL, et mes documents de formation.</p>${docs('../')}</section></section>`);
await page('pages/projets.html','Projets de formation',`<section class="wrap section page-section">${head('BTS SIO · PROJETS DE FORMATION','De la théorie à la pratique.','Les deux catégories de projets présentées dans mon portfolio de formation, avec les documents associés.')}<div class="two-columns"><article class="content-panel"><p class="eyebrow">01 / APPLICATION WEB</p><h2>Client léger</h2><p>Un client léger s’utilise depuis un navigateur et s’appuie sur une application côté serveur.</p><p class="muted">Le portfolio d’origine mentionne ce projet sans fiche détaillée. Le tableau de synthèse reste disponible pour consulter les réalisations de formation.</p><a class="button secondary" href="../src/files/${synthesis}"${ext}>Consulter le tableau E4 ↗</a></article><article class="content-panel"><p class="eyebrow">02 / APPLICATION INSTALLÉE</p><h2>Client lourd</h2><p>Un client lourd est une application installée sur un poste, avec son interface et sa logique d’exécution.</p><p class="muted">Le portfolio d’origine mentionne ce projet sans description technique détaillée. Les informations disponibles sont conservées sans ajout de résultats non documentés.</p><a class="button secondary" href="formations.html#documents">Documents de formation ↗</a></article></div><div class="section-heading subheading"><h2>Explorer les réalisations</h2><a class="text-link" href="realisations.html">La galerie complète ↗</a></div><div class="project-grid">${[projects[1],projects[2],projects[13]].map(project=>card(project,'../')).join('')}</div></section>`);
const feed=JSON.parse(await readFile('src/data/veille.json','utf8'));
const date=value=>new Date(value).toLocaleDateString('fr-FR',{day:'numeric',month:'long',year:'numeric'});
const article=item=>`<article class="news-card" data-source="${escape(item.sourceId)}"><div class="news-top"><span class="news-category">${escape(item.category)}</span><time datetime="${escape(item.publishedAt)}">${date(item.publishedAt)}</time></div><h2><a href="${escape(item.url)}"${ext}>${escape(item.title)}</a></h2><p>${escape(item.context)}</p><div class="news-bottom"><span>${escape(item.source)}</span><a href="${escape(item.url)}"${ext} aria-label="Lire ${escape(item.title)}">Lire à la source ↗</a></div></article>`;
await page('pages/veille.html','Journal de veille',`<section class="wrap section page-section">${head('LE JOURNAL · VEILLE TECHNOLOGIQUE','Curieux, par nature.','Ce qui bouge dans le développement, les outils et le cloud. Une sélection de publications issues de sources techniques, actualisée automatiquement.')}<div class="watch-masthead"><div><span class="status-dot"></span><strong>Le fil de la tech</strong><span id="feed-status">Dernière vérification : ${date(feed.checkedAt)}</span></div><span class="feed-disclaimer">Publications externes · Titres dans leur langue d’origine</span></div><div class="news-filters" role="group" aria-label="Filtrer la veille"><button data-source-filter="all" aria-pressed="true">Tout le journal</button><button data-source-filter="mdn" aria-pressed="false">Développement web</button><button data-source-filter="github" aria-pressed="false">Outils & IA</button><button data-source-filter="cloudflare" aria-pressed="false">Cloud & sécurité</button></div><p class="results" id="news-count" role="status">${feed.articles.length} publications</p><div class="news-grid" id="news-grid">${feed.articles.map(article).join('')}</div><p id="news-empty" hidden>Aucune publication pour cette source pour le moment.</p><details class="feed-method"><summary>Comment cette veille est-elle alimentée ?</summary><p>Les flux RSS officiels de MDN Web Docs, GitHub Blog et Cloudflare Blog sont collectés automatiquement. Chaque carte indique sa source et la date originale de publication. Les articles restent sur le site de leur auteur. En cas d’indisponibilité d’une source, les dernières publications récupérées restent consultables.</p><div class="feed-sources">${feed.sources.map(source=>`<a href="${escape(source.url)}"${ext}>${escape(source.name)} · Flux RSS ↗</a>`).join('')}</div><p id="feed-health"></p><p>Mes autres outils de veille : Feedly pour les flux RSS, Google Alerts pour les mots-clés et OpenAI pour explorer les sujets liés à l’IA.</p></details></section>`);
await page('pages/contact.html','Contact',`<section class="wrap section page-section">${head('UN PROJET, UNE QUESTION, UNE OPPORTUNITÉ','Faisons connaissance.','Pour échanger autour d’un projet IT, de l’automatisation, de la cybersécurité ou de NexSecure, retrouvez-moi sur LinkedIn.')}<div class="two-columns"><a class="contact-card" href="${linkedin}"${ext}><span class="contact-icon">in</span><h2>Échangeons sur LinkedIn</h2><p>Le moyen le plus direct pour me contacter et découvrir mon actualité professionnelle.</p><span class="card-action">Ouvrir mon profil <span>↗</span></span></a><a class="contact-card" href="https://github.com/Sunlama0"${ext}><span class="contact-icon">&lt;/&gt;</span><h2>Retrouvez mon code</h2><p>Mes expérimentations et mes projets de développement sur GitHub.</p><span class="card-action">Explorer Sunlama0 <span>↗</span></span></a></div><section class="company-section"><div class="company-heading"><p class="eyebrow">MON ENTREPRISE</p><h2>NexSecure<span>↗</span></h2><p>Des solutions numériques<br>pour les besoins du terrain.</p></div><div class="company-content"><p>Avec NexSecure, j’accompagne les entreprises dans la création de sites web et d’applications métier, l’automatisation de leurs processus et la sécurisation de leur informatique.</p><div class="company-services"><span>Sites & applications</span><span>Automatisation</span><span>Cybersécurité</span><span>Gestion IT</span></div><a class="button" href="https://nexsecure.fr/"${ext}>Découvrir NexSecure <span>↗</span></a></div></section><div class="info-strip"><span>↓</span><p>Vous cherchez mon CV, mes certifications ou le tableau de synthèse ? <a href="formations.html#documents">Tous les documents sont ici ↗</a></p></div></section>`);
console.log('Site généré : expériences, formations, 7 réalisations, 10 expériences interactives et journal de veille.');

await generateDiscovery();
